package rules
import demo.model.WaterLevel;
import demo.model.Temperature;
import demo.model.Snow;
import demo.model.Rain;
import demo.model.Decision;
global demo.model.Result resultObj;


rule "Evacuation-situation rule"
	 when
        WaterLevel(isHigh() == true) and Rain(isHeavy() == true) or
        WaterLevel(isHigh() == true) and Rain(isHeavy() == false) and Snow(isALot() == true) and Temperature(isHigh() == true)
     then
        resultObj.setDecision(Decision.EVACUATION);
end
